### ISSUE TITLE
[Milestone 4] 測試與部署

### ISSUE THREAD

**Issue by chunghsien** [chunghsien/pinpin-springcraft#4]
#### 📚 說明

完成單元測試與整合測試，優化專案部署流程，並實作自動化部署（CI/CD），確保應用程式可穩定運行於生產環境。

#### ✅ 任務清單

* [ ] 單元測試撰寫

  * [ ] 使用 JUnit 5 撰寫 Controller/Service 層單元測試
  * [ ] 使用 Mockito 模擬 Repository 依賴
  * [ ] 驗證 JWT 驗證流程與例外處理
* [ ] 整合測試

  * [ ] 使用 Spring Boot Test 進行 API 整合測試
  * [ ] 驗證完整登入/認證流程
* [ ] Docker 部署優化

  * [ ] 撰寫精簡的 Dockerfile 並使用多階段建構減少映像檔大小
  * [ ] 確保 Docker 容器環境變數設定完整
* [ ] Docker Compose 優化

  * [ ] 將 Redis、PostgreSQL、Spring Boot 應用整合至同一組網路
  * [ ] 設定健康檢查與容器重啟策略
* [ ] CI/CD 流程建置

  * [ ] 使用 GitHub Actions / GitLab CI 實作自動化測試 + 打包 + 部署
  * [ ] 設定環境變數與敏感資訊管理（可使用 GitHub Secrets）
  * [ ] 驗證自動化部署後應用程式能正確啟動
* [ ] 生產環境部署驗證

  * [ ] 測試部署版本穩定性
  * [ ] 驗證 Redis 快取、JWT 認證及資料庫連線皆正常

#### 📖 GitHub Actions 部署範例

```yaml
name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Build with Gradle
      run: ./gradlew build
    - name: Build Docker Image
      run: docker build -t ecommerce-api .
    - name: Push Docker Image (Optional)
      run: echo "Add your Docker Hub or Registry push commands here"
```

#### 📅 預計完成時間

* 7 天內

#### 👨‍💻 負責人

* @chunghsien

---
